### ISSUE TITLE
The link to the documentation leads to malware/advertisement sites

### ISSUE THREAD

**Issue by IntrepidPig** [kenz-gelsoft/wxRust#41]
The rust-ci.org domain is now for sale. When I first visited the link, it lead to a beeping page warning about iOS malware that both ublock origin and firefox warned me about. Now it just leads me to the domain sale page.

**Comment by kenz-gelsoft** [comment]
Thanks for reporting. I've deleted obsoleter branches, and remove links to rust-ci.org of alive branches.
(Though I've gave up maintaining this project effectively...)
